# Generated by Django 5.0.6 on 2024-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlkalinityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_hcl_phenolphthalein', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume_hcl_methyl_orange', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HardnessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edta_molarity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('edta_volume', models.DecimalField(decimal_places=5, max_digits=10)),
                ('znso4_volume', models.DecimalField(decimal_places=5, max_digits=10)),
                ('znso4_concentration', models.DecimalField(decimal_places=5, default=0.01, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pHReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TDSMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_dish_filtrate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('weight_dish', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume_sample', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TurbidityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_cm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
